if(input()=='vertebrado'):
    if(input()=='ave'):
        if(input()=='carnivoro'):
            print('aguia')
        else:
            print('pomba')
    else:
        if(input()=='onivoro'):
            print('homem')
        else:
            print('vaca')
else:
    if(input()=='inseto'):
        if(input()=='hematofago'):
            print('pulga')
        else:
            print("lagarta")
    else:
        if(input()=='hematofago'):
           print('sanguessuga')
        else:
            print('minhoca')
